package entity;
// Generated Apr 1, 2018 12:51:15 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProOrder generated by hbm2java
 */
public class ProOrder  implements java.io.Serializable {


     private Integer orderId;
     private DeliveryCost deliveryCost;
     private ShopUser1 shopUser1;
     private int proId;
     private Date orderDate;
     private int orderQty;
     private double totalPrice;
     private String orderStatus;
     private Set proOrderDetailses = new HashSet(0);

    public ProOrder() {
    }

	
    public ProOrder(DeliveryCost deliveryCost, ShopUser1 shopUser1, int proId, Date orderDate, int orderQty, double totalPrice, String orderStatus) {
        this.deliveryCost = deliveryCost;
        this.shopUser1 = shopUser1;
        this.proId = proId;
        this.orderDate = orderDate;
        this.orderQty = orderQty;
        this.totalPrice = totalPrice;
        this.orderStatus = orderStatus;
    }
    public ProOrder(DeliveryCost deliveryCost, ShopUser1 shopUser1, int proId, Date orderDate, int orderQty, double totalPrice, String orderStatus, Set proOrderDetailses) {
       this.deliveryCost = deliveryCost;
       this.shopUser1 = shopUser1;
       this.proId = proId;
       this.orderDate = orderDate;
       this.orderQty = orderQty;
       this.totalPrice = totalPrice;
       this.orderStatus = orderStatus;
       this.proOrderDetailses = proOrderDetailses;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public DeliveryCost getDeliveryCost() {
        return this.deliveryCost;
    }
    
    public void setDeliveryCost(DeliveryCost deliveryCost) {
        this.deliveryCost = deliveryCost;
    }
    public ShopUser1 getShopUser1() {
        return this.shopUser1;
    }
    
    public void setShopUser1(ShopUser1 shopUser1) {
        this.shopUser1 = shopUser1;
    }
    public int getProId() {
        return this.proId;
    }
    
    public void setProId(int proId) {
        this.proId = proId;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public int getOrderQty() {
        return this.orderQty;
    }
    
    public void setOrderQty(int orderQty) {
        this.orderQty = orderQty;
    }
    public double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }
    public Set getProOrderDetailses() {
        return this.proOrderDetailses;
    }
    
    public void setProOrderDetailses(Set proOrderDetailses) {
        this.proOrderDetailses = proOrderDetailses;
    }




}


